name: Build and Deploy to Cloud Run

on:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3 # git clone

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2

      - name: Install dependencies
        run: npm install

      - name: Run build
        run: npm run build

      - uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: 'build'
          target: '~/demo'

      - name: Run Deploy
        uses: appleboy/ssh-action@master
        with:
          command_timeout: 4m
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo rm -rf /var/www/jiangshuuu.com/blog
            sudo cp -R /home/ubuntu/demo/build /var/www/jiangshuuu.com/blog
